
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/nishu/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Windows - 10.0.22635 - AMD64
...
